import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync, existsSync } from 'node:fs'

const wrapper = readFileSync(new URL('../auth-worker/src/production-entrypoint-miniapp.ts', import.meta.url), 'utf8')
const primaryLogin = readFileSync(new URL('../auth-worker/src/telegram-primary-login.ts', import.meta.url), 'utf8')
const telegramAccount = readFileSync(new URL('../auth-worker/src/telegram-account.ts', import.meta.url), 'utf8')
const miniAuth = readFileSync(new URL('../auth-worker/src/telegram-miniapp.ts', import.meta.url), 'utf8')
const proxy = readFileSync(new URL('../src/app/api/auth/telegram/[...path]/route.ts', import.meta.url), 'utf8')
const signIn = readFileSync(new URL('../src/app/sign-in/page.tsx', import.meta.url), 'utf8')
const config = readFileSync(new URL('../next.config.mjs', import.meta.url), 'utf8')
const router = readFileSync(new URL('../src/production-router.mjs', import.meta.url), 'utf8')
const wrangler = readFileSync(new URL('../auth-worker/wrangler.toml', import.meta.url), 'utf8')
const secretWorkflowUrl = new URL('../.github/workflows/telegram-auth-secret.yml', import.meta.url)

test('Telegram browser Sign-In is first-class OIDC while Mini App uses Secrets Store HMAC', () => {
  assert.match(wrapper, /TELEGRAM_MINIAPP_BOT_TOKEN/)
  assert.match(wrapper, /handleTelegramPrimaryLogin/)
  assert.match(wrapper, /return worker\.fetch\(request, env\)/)
  assert.match(primaryLogin, /STATE_PREFIX = 'telegram_primary_oidc:'/)
  assert.match(primaryLogin, /code_challenge_method', 'S256'/)
  assert.match(primaryLogin, /claims\.nonce !== nonce/)
  assert.match(telegramAccount, /provider_subject = \?/)
  assert.match(primaryLogin, /createOrGetTelegramUser/)
  assert.match(telegramAccount, /INSERT INTO linked_identities/)
  assert.doesNotMatch(primaryLogin, /identity\.invalid/)
  assert.match(miniAuth, /WebAppData/)
  assert.match(miniAuth, /TELEGRAM_BOT_TOKEN\?\.get/)
  assert.match(miniAuth, /constantTimeHexEqual/)
  assert.match(miniAuth, /authDate < now - MAX_AGE_SECONDS/)
  assert.match(miniAuth, /createOrGetTelegramUser/)
  assert.match(miniAuth, /created_or_logged_in/)
  assert.doesNotMatch(miniAuth, /OTYA_ACCOUNT_REQUIRED/)
})

test('Telegram OIDC start persists PKCE and registration intent in KV without D1 access', () => {
  const startBlock = primaryLogin.slice(primaryLogin.indexOf('async function start'), primaryLogin.indexOf('async function callback'))
  assert.match(startBlock, /AUTH_KV\.put/)
  assert.match(startBlock, /code_challenge_method', 'S256'/)
  assert.match(startBlock, /mode !== 'login' && mode !== 'register'/)
  assert.match(startBlock, /terms_version === TERMS_VERSION/)
  assert.match(startBlock, /privacy_version === PRIVACY_VERSION/)
  assert.doesNotMatch(startBlock, /AUTH_DB|assertSchemaReady/)
})

test('Telegram sign-in cannot silently create a new Otya account', () => {
  const resolver = primaryLogin.slice(primaryLogin.indexOf('async function resolveTelegramLogin'), primaryLogin.indexOf('async function applyVerifiedPhone'))
  assert.doesNotMatch(resolver, /createOrGetTelegramUser/)
  assert.match(primaryLogin, /stored\.mode === 'login'/)
  assert.match(primaryLogin, /telegram=not-linked/)
  assert.match(primaryLogin, /stored\.mode === 'login'[\s\S]*resolveTelegramLogin/)
  assert.match(primaryLogin, /else \{[\s\S]*createOrGetTelegramUser/)
  assert.match(primaryLogin, /recordRegistrationConsent\(env, user\.id, stored\.marketingConsent === true\)/)
})

test('Telegram registration intent and legal acceptance come from the Otya registration UI', () => {
  const startTelegram = signIn.slice(signIn.indexOf('async function startTelegram'), signIn.indexOf('async function resendVerification'))
  assert.match(startTelegram, /registration \? 'register' : 'login'/)
  assert.match(startTelegram, /terms_accepted: true/)
  assert.match(startTelegram, /terms_version: TERMS_VERSION/)
  assert.match(startTelegram, /privacy_accepted: true/)
  assert.match(startTelegram, /privacy_version: PRIVACY_VERSION/)
  assert.match(startTelegram, /marketing_consent: marketing/)
})

test('Telegram web session is shared securely with Space and tokens stay out of JSON', () => {
  assert.match(proxy, /AUTH_PREFIX\s*=\s*'\/auth\/telegram\/'/)
  assert.match(proxy, /\.AUTH as AuthService/)
  assert.match(proxy, /__Secure-otya_access/)
  assert.match(proxy, /__Secure-otya_refresh/)
  assert.match(proxy, /COOKIE_DOMAIN = '\.petersmartlink\.com'/)
  assert.match(proxy, /SPACE_URL = 'https:\/\/space\.petersmartlink\.com\/'/)
  assert.match(proxy, /delete safe\.access_token/)
  assert.match(proxy, /delete safe\.refresh_token/)
})

test('Google and Telegram browser origins are enforced around the generated OpenNext worker', () => {
  assert.match(config, /https:\/\/accounts\.google\.com/)
  assert.match(config, /https:\/\/telegram\.org/)
  assert.match(config, /frame-ancestors 'none'/)
  assert.match(router, /CANONICAL_CSP/)
  assert.match(router, /import openNextWorker from '\.\.\/\.open-next\/worker\.js'/)
  assert.match(router, /script-src[^\n]*accounts\.google\.com/)
  assert.match(router, /connect-src[^\n]*accounts\.google\.com/)
  assert.match(router, /space\.petersmartlink\.com/)
  assert.match(router, /headers\.set\('Content-Security-Policy', CANONICAL_CSP\)/)
  assert.doesNotMatch(router, /unsafe-eval/)
})

test('auth reads Telegram bot credential from Cloudflare Secrets Store without GitHub duplication', () => {
  assert.match(wrangler, /\[\[secrets_store_secrets\]\]/)
  assert.match(wrangler, /binding\s*=\s*"TELEGRAM_MINIAPP_BOT_TOKEN"/)
  assert.match(wrangler, /secret_name\s*=\s*"TELEGRAM_BOT_TOKEN"/)
  assert.equal(existsSync(secretWorkflowUrl), false)
})
