version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "Africa/Kampala"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      backend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/auth-worker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:15"
      timezone: "Africa/Kampala"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      auth-worker-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:30"
      timezone: "Africa/Kampala"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      github-actions:
        patterns:
          - "*"
