'use client'
import { useCallback,useEffect,useRef,useState } from 'react'
import Link from 'next/link'

type Msg={id?:number;role:'user'|'assistant';content:string;created_at?:string}
type Conv={id:string;title:string;created_at:string;updated_at:string}
type Plugin={id:string;name:string;category:string;status:string;capabilities:string[];write:boolean;setup_hint?:string}
type Mail={id:string;from:string;from_email:string;subject:string;created_at:string;text?:string}
type AuthUser={id:string;email:string;name?:string|null}

export default function ConsoleClient(){
 const[token,setToken]=useState('');const[refreshToken,setRefreshToken]=useState('');const[user,setUser]=useState<AuthUser|null>(null);const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[authBusy,setAuthBusy]=useState(false)
 const[twoFactor,setTwoFactor]=useState(false);const[recoveryMode,setRecoveryMode]=useState(false);const[factorCode,setFactorCode]=useState('')
 const[view,setView]=useState<'chat'|'support'|'connections'>('chat');const[convs,setConvs]=useState<Conv[]>([]);const[current,setCurrent]=useState<string>('');const[messages,setMessages]=useState<Msg[]>([]);const[input,setInput]=useState('');const[busy,setBusy]=useState(false);const[notice,setNotice]=useState('');const[sidebar,setSidebar]=useState(false)
 const[plugins,setPlugins]=useState<Plugin[]>([]);const[inbox,setInbox]=useState<Mail[]>([]);const[selected,setSelected]=useState<Mail|null>(null);const[reply,setReply]=useState('')
 const scrollRef=useRef<HTMLDivElement>(null)

 useEffect(()=>{const t=sessionStorage.getItem('otya_access_token')||'';const r=sessionStorage.getItem('otya_refresh_token')||'';const raw=sessionStorage.getItem('otya_admin_user');if(t){setToken(t);setRefreshToken(r);try{if(raw)setUser(JSON.parse(raw))}catch{}}},[])
 useEffect(()=>{requestAnimationFrame(()=>{const el=scrollRef.current;if(el)el.scrollTo({top:el.scrollHeight,behavior:'smooth'})})},[messages,busy])
 const clearSession=useCallback(()=>{sessionStorage.removeItem('otya_access_token');sessionStorage.removeItem('otya_refresh_token');sessionStorage.removeItem('otya_admin_user');setToken('');setRefreshToken('');setUser(null)},[])
 const refreshAccess=useCallback(async()=>{if(!refreshToken)return'';const r=await fetch('/auth/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh_token:refreshToken})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)return'';sessionStorage.setItem('otya_access_token',d.access_token);setToken(d.access_token);if(d.user){sessionStorage.setItem('otya_admin_user',JSON.stringify(d.user));setUser(d.user)}return d.access_token as string},[refreshToken])
 const req=useCallback(async(url:string,init?:RequestInit)=>{let currentToken=token;let r=await fetch(url,{...init,headers:{Authorization:`Bearer ${currentToken}`,'Content-Type':'application/json',...(init?.headers||{})}});if(r.status===401&&refreshToken){const next=await refreshAccess();if(next){currentToken=next;r=await fetch(url,{...init,headers:{Authorization:`Bearer ${currentToken}`,'Content-Type':'application/json',...(init?.headers||{})}})}}const d=await r.json().catch(()=>({}));if(r.status===401){clearSession();throw new Error('Your admin session expired. Sign in again.')}if(r.status===403)throw new Error('This OTYA account is not authorized as an administrator.');if(!r.ok)throw new Error(d.detail||d.error||`HTTP ${r.status}`);return d},[token,refreshToken,refreshAccess,clearSession])
 const loadConvs=useCallback(async()=>{if(!token)return;const d=await req('/api/admin/ai/console/conversations');setConvs(d.conversations||[])},[req,token])
 const loadPlugins=useCallback(async()=>{if(!token)return;const d=await req('/api/admin/ai/console/plugins');setPlugins(d.plugins||[])},[req,token])
 const loadInbox=useCallback(async()=>{if(!token)return;const d=await req('/api/admin/ai/support/inbox?limit=30');setInbox(d.emails||[])},[req,token])
 useEffect(()=>{if(token){loadConvs().catch(e=>setNotice((e as Error).message));loadPlugins().catch(e=>setNotice((e as Error).message))}},[token,loadConvs,loadPlugins])

 function resetFactor(){setTwoFactor(false);setRecoveryMode(false);setFactorCode('')}
 async function login(e:React.FormEvent){e.preventDefault();if(!email.trim()||!password||twoFactor&&!factorCode.trim())return;setAuthBusy(true);setNotice('');try{const payload:Record<string,string>={email:email.trim(),password};if(twoFactor)payload[recoveryMode?'recovery_code':'totp_code']=factorCode.trim();const r=await fetch('/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok){if(d.code==='TWO_FACTOR_REQUIRED'||d.code==='TWO_FACTOR_INVALID'){setTwoFactor(true);setFactorCode('');throw new Error(d.code==='TWO_FACTOR_INVALID'?'That verification code was not accepted.':'Enter your two-step verification code.')}throw new Error(d.error||'Sign in failed')}const access=d.access_token as string;const refresh=d.refresh_token as string;sessionStorage.setItem('otya_access_token',access);sessionStorage.setItem('otya_refresh_token',refresh||'');sessionStorage.setItem('otya_admin_user',JSON.stringify(d.user||{}));setToken(access);setRefreshToken(refresh||'');setUser(d.user||null);resetFactor();const check=await fetch('/api/admin/ai/console/plugins',{headers:{Authorization:`Bearer ${access}`}});if(check.status===403){clearSession();throw new Error('This OTYA account is not authorized as an administrator.')}if(!check.ok){clearSession();throw new Error('Administrator access could not be verified.')}setPlugins((await check.json()).plugins||[])}catch(e){setNotice((e as Error).message)}finally{setAuthBusy(false)}}
 async function logout(){try{if(refreshToken)await fetch('/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh_token:refreshToken})})}catch{}clearSession()}
 async function openConv(id:string){setBusy(true);try{const d=await req(`/api/admin/ai/console/conversation?id=${encodeURIComponent(id)}`);setCurrent(id);setMessages((d.conversation?.messages||[]).map((m:Msg)=>({role:m.role,content:m.content,id:m.id,created_at:m.created_at})));setView('chat');setSidebar(false)}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}
 async function newChat(){setBusy(true);try{const d=await req('/api/admin/ai/console/conversation/new',{method:'POST'});setCurrent(d.conversation.id);setMessages([]);setView('chat');setSidebar(false);await loadConvs()}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}
 async function send(){const text=input.trim();if(!text||busy)return;setInput('');setMessages(m=>[...m,{role:'user',content:text}]);setBusy(true);setNotice('');try{const d=await req('/api/admin/ai/console/chat',{method:'POST',body:JSON.stringify({message:text,conversation_id:current||undefined})});setCurrent(d.conversation_id);setMessages(m=>[...m,{role:'assistant',content:d.answer||'No response.'}]);await loadConvs()}catch(e){setMessages(m=>[...m,{role:'assistant',content:`I could not complete that request: ${(e as Error).message}`}])}finally{setBusy(false)}}
 async function connectGmail(){setBusy(true);try{const d=await req('/api/admin/ai/connectors/gmail/start',{method:'POST'});window.location.assign(d.authorization_url)}catch(e){setNotice((e as Error).message);setBusy(false)}}
 async function openMail(id:string){setBusy(true);try{const d=await req(`/api/admin/ai/support/email?id=${encodeURIComponent(id)}`);setSelected(d.email);setReply('')}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}
 async function draft(){if(!selected)return;setBusy(true);try{const d=await req('/api/admin/ai/support/draft',{method:'POST',body:JSON.stringify({email_id:selected.id})});setReply(d.draft?.reply||'')}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}
 async function sendReply(){if(!selected||!reply.trim()||!confirm(`Send this reply to ${selected.from_email}?`))return;setBusy(true);try{await req('/api/admin/ai/support/send',{method:'POST',body:JSON.stringify({email_id:selected.id,reply:reply.trim(),risk:'manual'})});setNotice('Support reply sent.')}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}

 if(!token)return <main className="min-h-screen grid place-items-center p-4" style={{background:'var(--cosmos-scaffold)',color:'var(--cosmos-text-primary)'}}><form onSubmit={login} className="w-full max-w-sm rounded-2xl border p-5" style={{background:'var(--cosmos-card)',borderColor:'var(--cosmos-divider)'}}><div className="otya-kicker mb-2">OTYA Console</div><h1 className="text-2xl font-semibold tracking-[-.035em]">{twoFactor?'Verify it’s you':'Administrator sign in'}</h1><p className="text-sm otya-muted mt-2 mb-5">{twoFactor?(recoveryMode?'Enter an unused recovery code.':'Enter the 6-digit code from your authenticator app.'):'Private operations access for authorized OTYA administrators.'}</p>{notice&&<div className="border rounded-lg p-2.5 text-sm mb-3 text-red-500" style={{borderColor:'color-mix(in srgb, var(--cosmos-error) 30%, transparent)'}}>{notice}</div>}{!twoFactor?<><input className="w-full rounded-lg border px-3 py-2.5 bg-transparent mb-2.5" style={{borderColor:'var(--cosmos-divider)'}} type="email" autoComplete="email" placeholder="Admin email" value={email} onChange={e=>setEmail(e.target.value)}/><input className="w-full rounded-lg border px-3 py-2.5 bg-transparent" style={{borderColor:'var(--cosmos-divider)'}} type="password" autoComplete="current-password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/></>:<input autoFocus className="w-full rounded-lg border px-3 py-3 bg-transparent text-center tracking-[.15em]" style={{borderColor:'var(--cosmos-divider)'}} inputMode={recoveryMode?'text':'numeric'} autoComplete="one-time-code" placeholder={recoveryMode?'Recovery code':'000000'} value={factorCode} onChange={e=>setFactorCode(recoveryMode?e.target.value:e.target.value.replace(/\D/g,'').slice(0,6))}/>}<button disabled={authBusy} className="cosmos-button w-full rounded-lg py-2.5 mt-3 text-sm font-semibold">{authBusy?'Checking…':twoFactor?'Continue':'Sign in'}</button>{twoFactor&&<button type="button" onClick={()=>{setRecoveryMode(v=>!v);setFactorCode('');setNotice('')}} className="w-full mt-2 text-xs otya-muted">{recoveryMode?'Use authenticator code':'Use recovery code'}</button>}<div className="mt-4 pt-4 border-t flex justify-between text-xs otya-muted" style={{borderColor:'var(--cosmos-divider)'}}><Link href="/account">Account</Link><Link href="/">OTYA</Link></div></form></main>

 const title=view==='chat'?'Console':view==='support'?'Support':'Connections'
 return <main className="h-[100dvh] overflow-hidden flex" style={{background:'var(--cosmos-scaffold)',color:'var(--cosmos-text-primary)'}}>
   {sidebar&&<button className="fixed inset-0 z-30 bg-black/30 md:hidden" aria-label="Close navigation" onClick={()=>setSidebar(false)}/>} 
   <aside className={`${sidebar?'translate-x-0':'-translate-x-full'} md:translate-x-0 fixed md:static inset-y-0 left-0 z-40 w-[244px] shrink-0 border-r flex flex-col transition-transform duration-150`} style={{background:'var(--cosmos-surface)',borderColor:'var(--cosmos-divider)'}}>
     <div className="h-13 px-3 flex items-center border-b" style={{borderColor:'var(--cosmos-divider)'}}><span className="font-semibold text-sm">OTYA Console</span><button className="ml-auto md:hidden" onClick={()=>setSidebar(false)}>×</button></div>
     <div className="p-2.5"><button onClick={newChat} className="w-full rounded-lg border px-3 py-2 text-left text-sm font-medium" style={{borderColor:'var(--cosmos-divider)'}}>New conversation</button></div>
     <nav className="px-1.5 pb-2 text-[13px]">
       <button onClick={()=>{setView('chat');setSidebar(false)}} className="w-full text-left rounded-lg px-2.5 py-2" style={{fontWeight:view==='chat'?600:450}}>Console</button>
       <button onClick={()=>{setView('support');void loadInbox();setSidebar(false)}} className="w-full text-left rounded-lg px-2.5 py-2" style={{fontWeight:view==='support'?600:450}}>Support</button>
       <button onClick={()=>{setView('connections');setSidebar(false)}} className="w-full text-left rounded-lg px-2.5 py-2" style={{fontWeight:view==='connections'?600:450}}>Connections</button>
     </nav>
     <div className="px-3 pt-3 pb-2 text-[10px] uppercase tracking-[.12em] otya-muted">Conversations</div>
     <div className="overflow-auto flex-1 px-1.5">{convs.map(c=><button key={c.id} onClick={()=>void openConv(c.id)} className="w-full text-left rounded-lg px-2.5 py-2 text-[13px] truncate mb-0.5" style={{background:current===c.id?'color-mix(in srgb, var(--cosmos-text-primary) 6%, transparent)':'transparent',fontWeight:current===c.id?600:450}}>{c.title||'Conversation'}</button>)}</div>
     <div className="p-2 border-t text-xs" style={{borderColor:'var(--cosmos-divider)'}}><div className="px-2 py-1 truncate otya-muted">{user?.email}</div><button onClick={logout} className="w-full text-left rounded-lg px-2 py-2">Sign out</button></div>
   </aside>

   <section className="flex-1 min-w-0 flex flex-col">
     <header className="h-13 border-b flex items-center px-3 sm:px-4" style={{borderColor:'var(--cosmos-divider)',background:'var(--cosmos-app-bar)'}}><button className="md:hidden w-8 h-8 mr-1" onClick={()=>setSidebar(true)}>☰</button><div className="font-semibold text-sm">{title}</div><div className="ml-auto text-[11px] otya-muted">Private admin</div></header>
     {notice&&<div className="mx-4 mt-3 border rounded-lg px-3 py-2 text-sm" style={{borderColor:'var(--cosmos-divider)'}}>{notice}</div>}

     {view==='chat'&&<>
       <div ref={scrollRef} className="flex-1 overflow-auto"><div className="otya-reading py-7 pb-32">
         {messages.length===0&&<div className="min-h-[55vh] flex flex-col justify-center"><div className="otya-kicker mb-3">Private operator</div><h1 className="text-3xl sm:text-4xl font-semibold tracking-[-.04em]">What needs attention?</h1><p className="text-sm sm:text-[15px] otya-muted mt-3 max-w-lg">Ask for health, crashes, support, releases, feedback, connected tools, or a full operations report. Read-only checks can run automatically; external writes require approval.</p><div className="grid sm:grid-cols-2 gap-px border rounded-xl overflow-hidden mt-7" style={{borderColor:'var(--cosmos-divider)',background:'var(--cosmos-divider)'}}>{['What needs my attention today?','Summarize recent crashes','Review support messages','Give me the full OTYA report'].map(x=><button key={x} onClick={()=>setInput(x)} className="p-3.5 text-left text-sm" style={{background:'var(--cosmos-card)'}}>{x}</button>)}</div></div>}
         <div className="space-y-8">{messages.map((m,i)=>m.role==='user'?<div key={i} className="flex justify-end"><div className="max-w-[84%] rounded-2xl px-4 py-2.5 text-[15px] whitespace-pre-wrap" style={{background:'color-mix(in srgb, var(--cosmos-text-primary) 7%, var(--cosmos-card))'}}>{m.content}</div></div>:<article key={i}><div className="text-[11px] font-semibold mb-2 otya-muted">OTYA</div><div className="whitespace-pre-wrap text-[15px] sm:text-[16px] leading-7">{m.content}</div></article>)}{busy&&<div className="text-sm otya-muted animate-pulse">Checking OTYA…</div>}</div>
       </div></div>
       <div className="absolute md:left-[244px] left-0 right-0 bottom-0 px-3 sm:px-4 pb-[max(10px,env(safe-area-inset-bottom))] pt-6" style={{background:'linear-gradient(to top,var(--cosmos-scaffold) 72%,transparent)'}}><div className="otya-reading"><div className="rounded-2xl border p-1.5 flex items-end" style={{background:'var(--cosmos-card)',borderColor:'var(--cosmos-divider)'}}><textarea rows={1} className="min-h-10 max-h-36 flex-1 resize-none bg-transparent px-3 py-2 outline-none text-[15px]" placeholder="Ask OTYA Console" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}}}/><button onClick={()=>void send()} disabled={busy||!input.trim()} className="cosmos-button w-9 h-9 rounded-xl disabled:opacity-30">↑</button></div><p className="text-[10px] otya-muted text-center mt-1.5">Read operations may run automatically. External writes require approval.</p></div></div>
     </>}

     {view==='connections'&&<div className="flex-1 overflow-auto"><div className="otya-shell max-w-4xl py-8"><div className="mb-6"><div className="otya-kicker mb-2">Integrations</div><h2 className="text-2xl font-semibold tracking-tight">Connections</h2></div><div className="border-y" style={{borderColor:'var(--cosmos-divider)'}}>{plugins.map((p,index)=><div key={p.id} className={`grid sm:grid-cols-[130px_1fr_auto] gap-2 sm:gap-5 py-4 ${index<plugins.length-1?'border-b':''}`} style={{borderColor:'var(--cosmos-divider)'}}><div><strong className="text-sm">{p.name}</strong><div className="text-[11px] otya-muted mt-1">{p.category}</div></div><div><p className="text-sm otya-muted">{p.capabilities.join(' · ')}</p>{p.setup_hint&&<p className="text-xs otya-muted mt-1">{p.setup_hint}</p>}</div><div className="text-xs font-medium sm:text-right"><div>{p.status.replaceAll('_',' ')}</div>{p.id==='gmail'&&p.status==='ready_to_connect'&&<button onClick={()=>void connectGmail()} className="mt-2 text-xs font-semibold">Connect →</button>}</div></div>)}</div></div></div>}

     {view==='support'&&<div className="flex-1 overflow-hidden grid lg:grid-cols-[310px_1fr]"><div className="border-r overflow-auto" style={{borderColor:'var(--cosmos-divider)'}}>{inbox.length===0?<div className="p-4 text-sm otya-muted">No support messages loaded.</div>:inbox.map(m=><button key={m.id} onClick={()=>void openMail(m.id)} className="w-full text-left px-4 py-3.5 border-b" style={{borderColor:'var(--cosmos-divider)',background:selected?.id===m.id?'color-mix(in srgb, var(--cosmos-text-primary) 4%, transparent)':'transparent'}}><strong className="text-[13px] block truncate">{m.from}</strong><span className="text-[13px] block truncate mt-0.5 otya-muted">{m.subject}</span></button>)}</div><div className="overflow-auto p-5 sm:p-7">{!selected?<div className="max-w-xl"><div className="otya-kicker mb-2">Support</div><h2 className="text-2xl font-semibold">Select a message</h2><p className="text-sm otya-muted mt-2">OTYA AI can draft a reply. Sending still requires your explicit approval.</p></div>:<div className="max-w-2xl"><div className="text-xs otya-muted">{selected.from}</div><h2 className="text-xl font-semibold mt-1">{selected.subject}</h2><div className="border-y py-4 mt-5 whitespace-pre-wrap text-sm leading-6" style={{borderColor:'var(--cosmos-divider)'}}>{selected.text}</div><button onClick={()=>void draft()} className="otya-quiet-button rounded-lg px-3.5 py-2 mt-4 text-sm font-semibold">Draft with OTYA</button>{reply&&<><textarea value={reply} onChange={e=>setReply(e.target.value)} rows={10} className="w-full rounded-xl border p-3 mt-4 bg-transparent text-sm leading-6" style={{borderColor:'var(--cosmos-divider)'}}/><button onClick={()=>void sendReply()} className="cosmos-button rounded-lg px-4 py-2 mt-3 text-sm font-semibold">Approve & send</button></>}</div>}</div></div>}
   </section>
 </main>
}
