'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'

type Role='user'|'assistant'
type ChatMessage={id:string;role:Role;content:string;tool?:string|null}
type ChatSession={id:string;title:string;messages:ChatMessage[];updated:number}
type Plugin={id:string;name:string;category:string;status:string;capabilities:string[];write:boolean;setup_hint?:string}
type InboxEmail={id:string;from:string;from_email:string;subject:string;created_at:string;attachments:{id:string;filename:string;content_type:string;size?:number|null}[]}
type EmailDetail=InboxEmail&{text:string;message_id:string;reply_to:string[]}
type Draft={reply:string;risk:'low'|'medium'|'high';reason:string;category:string;requires_human:boolean}

type View='chat'|'support'|'settings'
const uid=()=>`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`
const fmt=(v:string)=>{try{return new Date(v).toLocaleString()}catch{return v}}
const newSession=():ChatSession=>({id:uid(),title:'New chat',messages:[],updated:Date.now()})

export default function OtyaConsole(){
  const[token,setToken]=useState('');const[tokenInput,setTokenInput]=useState('');const[view,setView]=useState<View>('chat')
  const[sessions,setSessions]=useState<ChatSession[]>([]);const[activeId,setActiveId]=useState('');const[input,setInput]=useState('')
  const[plugins,setPlugins]=useState<Plugin[]>([]);const[inbox,setInbox]=useState<InboxEmail[]>([]);const[selected,setSelected]=useState<EmailDetail|null>(null)
  const[draft,setDraft]=useState<Draft|null>(null);const[reply,setReply]=useState('');const[instruction,setInstruction]=useState('')
  const[busy,setBusy]=useState(false);const[notice,setNotice]=useState('');const[mobileMenu,setMobileMenu]=useState(false)

  useEffect(()=>{const saved=sessionStorage.getItem('otya_admin_token')||'';if(saved){setToken(saved);setTokenInput(saved)};try{const raw=localStorage.getItem('otya_console_chats');const parsed=raw?JSON.parse(raw):[];if(Array.isArray(parsed)&&parsed.length){setSessions(parsed);setActiveId(parsed[0].id)}else{const s=newSession();setSessions([s]);setActiveId(s.id)}}catch{const s=newSession();setSessions([s]);setActiveId(s.id)};if(new URLSearchParams(window.location.search).get('gmail')==='connected')setNotice('Gmail connected successfully.')},[])
  useEffect(()=>{if(sessions.length)localStorage.setItem('otya_console_chats',JSON.stringify(sessions.slice(0,30)))},[sessions])
  const headers=useMemo(()=>({Authorization:`Bearer ${token}`,'Content-Type':'application/json'}),[token])
  const request=useCallback(async(url:string,init?:RequestInit)=>{const r=await fetch(url,{...init,headers:{...headers,...(init?.headers||{})}});const d=await r.json().catch(()=>({}));if(r.status===401){sessionStorage.removeItem('otya_admin_token');setToken('');throw new Error('Admin session expired.')}if(!r.ok)throw new Error(d.detail||d.error||`HTTP ${r.status}`);return d},[headers])
  const active=sessions.find(s=>s.id===activeId)||sessions[0]

  const loadPlugins=useCallback(async()=>{if(!token)return;try{const d=await request('/api/admin/ai/console/plugins');setPlugins(d.plugins||[])}catch(e){setNotice((e as Error).message)}},[request,token])
  const loadInbox=useCallback(async()=>{if(!token)return;try{const d=await request('/api/admin/ai/support/inbox?limit=30');setInbox(d.emails||[])}catch(e){setNotice((e as Error).message)}},[request,token])
  useEffect(()=>{if(token){loadPlugins();loadInbox()}},[token,loadPlugins,loadInbox])

  function login(e:React.FormEvent){e.preventDefault();const v=tokenInput.trim();if(!v)return;sessionStorage.setItem('otya_admin_token',v);setToken(v)}
  function startChat(){const s=newSession();setSessions(prev=>[s,...prev]);setActiveId(s.id);setView('chat');setMobileMenu(false)}
  function removeChat(id:string){setSessions(prev=>{const next=prev.filter(s=>s.id!==id);if(!next.length){const n=newSession();setActiveId(n.id);return[n]}if(activeId===id)setActiveId(next[0].id);return next})}

  async function sendChat(){const text=input.trim();if(!text||!active||busy)return;setInput('');setBusy(true);setNotice('');const userMsg:ChatMessage={id:uid(),role:'user',content:text};const history=active.messages.map(m=>({role:m.role,content:m.content}));setSessions(prev=>prev.map(s=>s.id===active.id?{...s,title:s.messages.length?s.title:text.slice(0,42),messages:[...s.messages,userMsg],updated:Date.now()}:s));try{const d=await request('/api/admin/ai/console/chat',{method:'POST',body:JSON.stringify({message:text,history})});const aiMsg:ChatMessage={id:uid(),role:'assistant',content:d.answer||'No response.',tool:d.tool||null};setSessions(prev=>prev.map(s=>s.id===active.id?{...s,messages:[...s.messages,aiMsg],updated:Date.now()}:s))}catch(e){const err:ChatMessage={id:uid(),role:'assistant',content:`I couldn't complete that request: ${(e as Error).message}`};setSessions(prev=>prev.map(s=>s.id===active.id?{...s,messages:[...s.messages,err]}:s))}finally{setBusy(false)}}

  async function connectGmail(){setBusy(true);try{const d=await request('/api/admin/ai/connectors/gmail/start',{method:'POST'});if(!d.authorization_url)throw new Error('Google authorization URL unavailable.');window.location.assign(d.authorization_url)}catch(e){setNotice((e as Error).message);setBusy(false)}}
  async function openEmail(id:string){setBusy(true);setDraft(null);setReply('');setInstruction('');try{const d=await request(`/api/admin/ai/support/email?id=${encodeURIComponent(id)}`);setSelected(d.email)}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}
  async function makeDraft(){if(!selected)return;setBusy(true);try{const d=await request('/api/admin/ai/support/draft',{method:'POST',body:JSON.stringify({email_id:selected.id,instruction:instruction.trim()||undefined})});setDraft(d.draft);setReply(d.draft.reply||'')}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}
  async function sendReply(){if(!selected||!reply.trim())return;if(!window.confirm(`Send from support@petersmartlink.com to ${selected.from_email}?`))return;setBusy(true);try{const d=await request('/api/admin/ai/support/send',{method:'POST',body:JSON.stringify({email_id:selected.id,reply:reply.trim(),risk:draft?.risk||'manual'})});setNotice(`Reply sent to ${d.to}.`);await loadInbox()}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}

  if(!token)return <main className="min-h-screen grid place-items-center px-4" style={{background:'var(--cosmos-scaffold)'}}><form onSubmit={login} className="w-full max-w-sm rounded-2xl border p-7" style={{background:'var(--cosmos-card)',borderColor:'var(--cosmos-divider)'}}><p className="text-xs font-bold tracking-[.2em]" style={{color:'#7b61ff'}}>PETERSMART LINK</p><h1 className="text-2xl font-black mt-1" style={{color:'var(--cosmos-text-primary)'}}>OTYA Console</h1><p className="text-sm mt-2 mb-5" style={{color:'var(--cosmos-text-secondary)'}}>Private AI workspace</p><input type="password" value={tokenInput} onChange={e=>setTokenInput(e.target.value)} placeholder="Admin token" className="w-full rounded-xl border px-4 py-3" style={{background:'var(--cosmos-surface)',borderColor:'var(--cosmos-divider)',color:'var(--cosmos-text-primary)'}}/><button className="cosmos-button w-full rounded-xl py-3 font-bold mt-4">Open Console</button></form></main>

  const sidebar=<aside className="w-[280px] h-full border-r flex flex-col" style={{background:'var(--cosmos-card)',borderColor:'var(--cosmos-divider)'}}><div className="p-3"><button onClick={startChat} className="cosmos-button w-full rounded-xl py-2.5 font-bold text-sm">＋ New chat</button></div><nav className="px-2 space-y-1"><button onClick={()=>{setView('chat');setMobileMenu(false)}} className="w-full text-left rounded-xl px-3 py-2 text-sm" style={{background:view==='chat'?'rgba(123,97,255,.14)':'transparent'}}>◉ Chat</button><button onClick={()=>{setView('support');setMobileMenu(false)}} className="w-full text-left rounded-xl px-3 py-2 text-sm" style={{background:view==='support'?'rgba(123,97,255,.14)':'transparent'}}>✉ Support inbox</button></nav><div className="px-3 pt-5 text-[11px] font-bold tracking-widest" style={{color:'var(--cosmos-text-secondary)'}}>RECENT CHATS</div><div className="flex-1 overflow-auto px-2 py-2">{sessions.map(s=><div key={s.id} className="group flex items-center rounded-xl" style={{background:activeId===s.id&&view==='chat'?'rgba(123,97,255,.10)':'transparent'}}><button onClick={()=>{setActiveId(s.id);setView('chat');setMobileMenu(false)}} className="flex-1 min-w-0 text-left px-3 py-2 text-sm truncate">{s.title}</button><button onClick={()=>removeChat(s.id)} className="opacity-50 hover:opacity-100 px-2">×</button></div>)}</div><div className="border-t p-2 space-y-1" style={{borderColor:'var(--cosmos-divider)'}}><button onClick={()=>{setView('settings');setMobileMenu(false)}} className="w-full text-left rounded-xl px-3 py-2 text-sm" style={{background:view==='settings'?'rgba(123,97,255,.14)':'transparent'}}>⚙ Settings & plugins</button><button onClick={()=>{sessionStorage.removeItem('otya_admin_token');setToken('')}} className="w-full text-left rounded-xl px-3 py-2 text-sm">🔒 Lock Console</button></div></aside>

  return <main className="h-screen overflow-hidden" style={{background:'var(--cosmos-scaffold)',color:'var(--cosmos-text-primary)'}}><div className="h-full flex"><div className="hidden md:block h-full">{sidebar}</div>{mobileMenu&&<div className="fixed inset-0 z-40 md:hidden flex"><div className="h-full">{sidebar}</div><button onClick={()=>setMobileMenu(false)} className="flex-1 bg-black/40" aria-label="Close menu"/></div>}<section className="flex-1 min-w-0 h-full flex flex-col"><header className="h-14 border-b px-3 md:px-5 flex items-center justify-between" style={{borderColor:'var(--cosmos-divider)',background:'var(--cosmos-card)'}}><div className="flex items-center gap-3"><button className="md:hidden text-xl" onClick={()=>setMobileMenu(true)}>☰</button><div><strong>OTYA Console</strong><span className="hidden sm:inline text-xs ml-2" style={{color:'var(--cosmos-text-secondary)'}}>AI operator</span></div></div><div className="text-xs" style={{color:'var(--cosmos-text-secondary)'}}>{plugins.filter(p=>p.status==='connected').length} plugins connected</div></header>{notice&&<div className="mx-4 mt-3 rounded-xl border px-4 py-2 text-sm" style={{background:'var(--cosmos-card)',borderColor:'var(--cosmos-divider)'}}>{notice}<button onClick={()=>setNotice('')} className="float-right">×</button></div>}

  {view==='chat'&&<div className="flex-1 min-h-0 flex flex-col"><div className="flex-1 overflow-auto"><div className="max-w-3xl mx-auto px-4 py-8 space-y-6">{(!active||active.messages.length===0)&&<div className="min-h-[55vh] grid place-items-center text-center"><div><div className="w-14 h-14 rounded-2xl grid place-items-center mx-auto mb-4 text-2xl font-black" style={{background:'rgba(123,97,255,.16)',color:'#a99cff'}}>O</div><h1 className="text-3xl font-black">How can I help?</h1><p className="text-sm mt-2 max-w-lg" style={{color:'var(--cosmos-text-secondary)'}}>Ask about OTYA, support email, crashes, releases, users, infrastructure, connected tools, planning or writing.</p><div className="grid sm:grid-cols-2 gap-2 mt-6 max-w-xl">{['What should I fix next?','Summarize recent user feedback','Check my connected plugins','Help me plan the next OTYA release'].map(x=><button key={x} onClick={()=>setInput(x)} className="rounded-xl border p-3 text-left text-sm" style={{background:'var(--cosmos-card)',borderColor:'var(--cosmos-divider)'}}>{x}</button>)}</div></div></div>}{active?.messages.map(m=><div key={m.id} className={`flex ${m.role==='user'?'justify-end':'justify-start'}`}><div className={`max-w-[88%] rounded-2xl px-4 py-3 text-sm whitespace-pre-wrap ${m.role==='user'?'rounded-br-md':'rounded-bl-md'}`} style={{background:m.role==='user'?'rgba(123,97,255,.22)':'var(--cosmos-card)',border:m.role==='assistant'?'1px solid var(--cosmos-divider)':'none'}}>{m.content}{m.tool&&<div className="text-[10px] mt-2 opacity-60">Used {m.tool.replaceAll('_',' ')}</div>}</div></div>)}{busy&&<div className="text-sm" style={{color:'var(--cosmos-text-secondary)'}}>OTYA AI is thinking…</div>}</div></div><div className="px-4 pb-4"><div className="max-w-3xl mx-auto rounded-2xl border p-2 flex items-end gap-2" style={{background:'var(--cosmos-card)',borderColor:'var(--cosmos-divider)'}}><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendChat()}}} rows={1} placeholder="Message OTYA AI…" className="flex-1 resize-none bg-transparent outline-none px-3 py-2 text-sm max-h-36"/><button onClick={sendChat} disabled={busy||!input.trim()} className="cosmos-button rounded-xl px-4 py-2 font-bold disabled:opacity-40">↑</button></div><p className="text-[10px] text-center mt-2" style={{color:'var(--cosmos-text-secondary)'}}>Write actions still require approval in their tool panel.</p></div></div>}

  {view==='support'&&<div className="flex-1 overflow-auto p-4 md:p-6"><div className="max-w-6xl mx-auto"><div className="mb-5"><h1 className="text-2xl font-black">Support inbox</h1><p className="text-sm" style={{color:'var(--cosmos-text-secondary)'}}>Resend Receiving → AI draft → your approval → support@petersmartlink.com</p></div><div className="grid lg:grid-cols-[340px_1fr] gap-4"><div className="rounded-2xl border overflow-hidden" style={{background:'var(--cosmos-card)',borderColor:'var(--cosmos-divider)'}}><div className="p-3 border-b flex justify-between" style={{borderColor:'var(--cosmos-divider)'}}><strong>Messages</strong><button onClick={loadInbox} className="text-xs">Refresh</button></div>{inbox.map(e=><button key={e.id} onClick={()=>openEmail(e.id)} className="w-full text-left p-3 border-b" style={{borderColor:'var(--cosmos-divider)',background:selected?.id===e.id?'rgba(123,97,255,.12)':'transparent'}}><div className="font-bold text-sm truncate">{e.from||e.from_email}</div><div className="text-sm truncate">{e.subject||'(no subject)'}</div><div className="text-xs mt-1" style={{color:'var(--cosmos-text-secondary)'}}>{fmt(e.created_at)}</div></button>)}</div><div className="rounded-2xl border p-5" style={{background:'var(--cosmos-card)',borderColor:'var(--cosmos-divider)'}}>{!selected?<div className="min-h-96 grid place-items-center text-sm" style={{color:'var(--cosmos-text-secondary)'}}>Choose an email.</div>:<div className="space-y-4"><div><div className="text-xs" style={{color:'var(--cosmos-text-secondary)'}}>FROM</div><strong>{selected.from}</strong><h2 className="text-xl font-black mt-2">{selected.subject}</h2></div><div className="rounded-xl border p-4 whitespace-pre-wrap text-sm max-h-64 overflow-auto" style={{borderColor:'var(--cosmos-divider)',background:'var(--cosmos-surface)'}}>{selected.text}</div><input value={instruction} onChange={e=>setInstruction(e.target.value)} placeholder="Optional instruction to AI" className="w-full rounded-xl border px-4 py-3 text-sm" style={{background:'var(--cosmos-surface)',borderColor:'var(--cosmos-divider)'}}/><button onClick={makeDraft} disabled={busy} className="cosmos-button rounded-xl px-4 py-2 font-bold text-sm">Draft reply</button>{draft&&<div className="text-xs rounded-xl border p-3" style={{borderColor:draft.risk==='high'?'#ef4444':draft.risk==='medium'?'#f59e0b':'#10b981'}}>Risk: {draft.risk.toUpperCase()} · {draft.category}{draft.requires_human?' · Human review required':''}</div>}{(draft||reply)&&<><textarea value={reply} onChange={e=>setReply(e.target.value)} rows={10} className="w-full rounded-xl border px-4 py-3 text-sm" style={{background:'var(--cosmos-surface)',borderColor:'var(--cosmos-divider)'}}/><div className="flex justify-end"><button onClick={sendReply} disabled={busy||!reply.trim()} className="rounded-xl bg-emerald-600 text-white px-5 py-2 font-bold text-sm">Approve & send</button></div></>}</div>}</div></div></div></div>}

  {view==='settings'&&<div className="flex-1 overflow-auto p-4 md:p-6"><div className="max-w-5xl mx-auto"><h1 className="text-2xl font-black">Settings</h1><p className="text-sm mt-1 mb-6" style={{color:'var(--cosmos-text-secondary)'}}>Manage the tools OTYA AI is allowed to use.</p><section className="rounded-2xl border p-5" style={{background:'var(--cosmos-card)',borderColor:'var(--cosmos-divider)'}}><div className="flex justify-between mb-4"><div><h2 className="font-black">Plugins & connections</h2><p className="text-xs mt-1" style={{color:'var(--cosmos-text-secondary)'}}>Credentials stay server-side. Connecting a plugin does not remove approval requirements.</p></div><button onClick={loadPlugins} className="text-sm">Refresh</button></div><div className="grid sm:grid-cols-2 gap-3">{plugins.map(p=><div key={p.id} className="rounded-xl border p-4" style={{background:'var(--cosmos-surface)',borderColor:'var(--cosmos-divider)'}}><div className="flex justify-between gap-3"><div><strong>{p.name}</strong><div className="text-[11px] mt-1" style={{color:'var(--cosmos-text-secondary)'}}>{p.category}</div></div><span className="text-[10px] h-fit rounded-full px-2 py-1" style={{background:p.status==='connected'?'rgba(16,185,129,.15)':'rgba(245,158,11,.15)',color:p.status==='connected'?'#34d399':'#fbbf24'}}>{p.status.replaceAll('_',' ')}</span></div><p className="text-xs mt-3" style={{color:'var(--cosmos-text-secondary)'}}>{p.capabilities.join(' · ')}</p>{p.setup_hint&&<p className="text-[11px] mt-3" style={{color:'var(--cosmos-text-secondary)'}}>{p.setup_hint}</p>}{p.id==='gmail'&&p.status==='ready_to_connect'&&<button onClick={connectGmail} className="cosmos-button rounded-lg px-3 py-2 text-xs font-bold mt-3">Connect Gmail</button>}</div>)}</div></section></div></div>}
  </section></div></main>
}
