'use client'

import {useEffect,useRef,useState} from 'react'

type M={role:'user'|'assistant';content:string}
type U={id:string;email:string;name?:string|null}
type C={id:string;title:string;created_at:string;updated_at:string}
type Model={id:string;name:string;provider:string;tier:string;description:string;guest?:boolean}
type Quota={limit:number;used:number;remaining:number;global_limit?:number;global_used?:number}

export default function OtyaAiPage(){
  const[guest,setGuest]=useState(''),[conversation,setConversation]=useState(''),[conversations,setConversations]=useState<C[]>([]),[messages,setMessages]=useState<M[]>([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const[token,setToken]=useState(''),[user,setUser]=useState<U|null>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[showLogin,setShowLogin]=useState(false),[authBusy,setAuthBusy]=useState(false)
  const[models,setModels]=useState<Model[]>([]),[model,setModel]=useState('llama-fast'),[sidebar,setSidebar]=useState(false),[forceNew,setForceNew]=useState(false),[quota,setQuota]=useState<Quota|null>(null)
  const scrollRef=useRef<HTMLDivElement>(null),textRef=useRef<HTMLTextAreaElement>(null)

  useEffect(()=>{let g=localStorage.getItem('otya_ai_guest')||'';if(!g){g=crypto.randomUUID()+crypto.randomUUID();localStorage.setItem('otya_ai_guest',g)}setGuest(g);const t=sessionStorage.getItem('otya_access_token')||'',raw=sessionStorage.getItem('otya_ai_user');if(t){setToken(t);try{if(raw)setUser(JSON.parse(raw))}catch{}}setConversation(t?(localStorage.getItem('otya_ai_conversation')||''):'')},[])
  useEffect(()=>{if(guest)void loadModels();if(token)void loadChats()},[token,guest])
  useEffect(()=>{if(token&&conversation)void loadConversation(conversation)},[token,conversation])
  useEffect(()=>{requestAnimationFrame(()=>{const el=scrollRef.current;if(el)el.scrollTo({top:el.scrollHeight,behavior:'smooth'})})},[messages,busy])

  function authHeaders(){const h:Record<string,string>={};if(token)h.Authorization=`Bearer ${token}`;return h}
  async function loadModels(){try{const suffix=guest?`&guest_id=${encodeURIComponent(guest)}`:'';const r=await fetch(`/api/ai/chat?models=1${suffix}`,{headers:authHeaders(),cache:'no-store'}),d=await r.json();if(r.ok){setModels(d.models||[]);setQuota(d.quota||null);const saved=localStorage.getItem('otya_ai_model')||d.default_model||d.guest_model||'llama-fast',allowed=(d.models||[]).some((m:Model)=>m.id===saved);setModel(allowed?saved:(d.default_model||d.guest_model||'llama-fast'))}}catch{}}
  async function loadChats(){try{const r=await fetch('/api/ai/chat?list=1',{headers:authHeaders(),cache:'no-store'}),d=await r.json();if(r.ok)setConversations(d.conversations||[])}catch{}}
  async function loadConversation(id:string){try{const r=await fetch(`/api/ai/chat?conversation_id=${encodeURIComponent(id)}`,{headers:authHeaders(),cache:'no-store'}),d=await r.json();if(r.ok){setMessages((d.conversation?.messages||[]).map((x:M)=>({role:x.role,content:x.content})));setConversation(id);localStorage.setItem('otya_ai_conversation',id);setForceNew(false);setSidebar(false)}}catch{}}

  async function login(e:React.FormEvent){e.preventDefault();if(!email.trim()||!password)return;setAuthBusy(true);setError('');try{const r=await fetch('/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:email.trim(),password})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Sign in failed');sessionStorage.setItem('otya_access_token',d.access_token);sessionStorage.setItem('otya_refresh_token',d.refresh_token||'');sessionStorage.setItem('otya_ai_user',JSON.stringify(d.user||{}));setToken(d.access_token);setUser(d.user||null);setShowLogin(false);setMessages([]);setConversation('');setForceNew(true)}catch(e){setError((e as Error).message)}finally{setAuthBusy(false)}}
  async function logout(){const refresh=sessionStorage.getItem('otya_refresh_token')||'';try{if(refresh)await fetch('/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh_token:refresh})})}catch{}sessionStorage.removeItem('otya_access_token');sessionStorage.removeItem('otya_refresh_token');sessionStorage.removeItem('otya_ai_user');setToken('');setUser(null);setConversation('');setConversations([]);setMessages([]);setModel('llama-fast');setQuota(null)}

  async function send(){const text=input.trim();if(!text||!guest||busy)return;const history=messages.slice(-20);setInput('');setMessages(v=>[...v,{role:'user',content:text}]);setBusy(true);setError('');try{const h=new Headers({'Content-Type':'application/json'});if(token)h.set('Authorization',`Bearer ${token}`);const r=await fetch('/api/ai/chat',{method:'POST',headers:h,body:JSON.stringify({message:text,guest_id:guest,conversation_id:token&&conversation?conversation:undefined,new_chat:Boolean(token&&forceNew),model:token?model:undefined,history:token?undefined:history})}),d=await r.json().catch(()=>({}));if(d.quota)setQuota(d.quota);if(!r.ok)throw new Error(d.error||'OTYA AI is unavailable');if(token&&d.conversation_id){setConversation(d.conversation_id);localStorage.setItem('otya_ai_conversation',d.conversation_id);setForceNew(false);void loadChats()}setMessages(v=>[...v,{role:'assistant',content:d.answer||'I could not answer that.'}])}catch(e){setError((e as Error).message)}finally{setBusy(false);textRef.current?.focus()}}
  function newChat(){if(token)localStorage.removeItem('otya_ai_conversation');setConversation('');setMessages([]);setError('');setForceNew(Boolean(token));setSidebar(false);setTimeout(()=>textRef.current?.focus(),50)}
  function chooseModel(id:string){if(!token)return;setModel(id);localStorage.setItem('otya_ai_model',id)}

  const selected=models.find(x=>x.id===model)
  return <main className="h-[100dvh] overflow-hidden flex" style={{background:'var(--cosmos-scaffold)',color:'var(--cosmos-text-primary)'}}>
    {sidebar&&<button aria-label="Close sidebar" className="fixed inset-0 z-30 bg-black/45 md:hidden" onClick={()=>setSidebar(false)}/>} 
    <aside className={`${sidebar?'translate-x-0':'-translate-x-full'} md:translate-x-0 fixed md:static inset-y-0 left-0 z-40 w-[278px] shrink-0 border-r transition-transform duration-200 flex flex-col`} style={{background:'var(--cosmos-card)',borderColor:'var(--cosmos-divider)'}}>
      <div className="p-3 flex items-center gap-2"><div className="w-9 h-9 rounded-xl grid place-items-center font-black text-white cosmos-button">O</div><div className="min-w-0"><div className="font-black">OTYA AI</div><div className="text-[11px] opacity-55">by PeterSmart Link</div></div><button className="ml-auto md:hidden text-xl" onClick={()=>setSidebar(false)}>×</button></div>
      <div className="px-3"><button onClick={newChat} className="w-full rounded-xl border px-3 py-2.5 text-left font-semibold" style={{borderColor:'var(--cosmos-divider)'}}>＋ New chat</button></div>
      {quota&&<div className="mx-3 mt-3 rounded-xl border p-3 text-xs" style={{borderColor:'var(--cosmos-divider)'}}><div className="flex justify-between gap-3"><span className="opacity-60">AI credits today</span><strong>{quota.remaining}/{quota.limit}</strong></div><div className="mt-2 h-1.5 rounded-full overflow-hidden" style={{background:'var(--cosmos-divider)'}}><div className="h-full rounded-full" style={{width:`${Math.max(0,Math.min(100,(quota.remaining/Math.max(1,quota.limit))*100))}%`,background:'var(--cosmos-primary)'}}/></div></div>}
      <div className="px-3 pt-5 pb-2 text-[11px] uppercase tracking-wider opacity-50">{token?'Recent chats':'Your chats'}</div>
      <div className="flex-1 overflow-y-auto px-2">{token?conversations.map(c=><button key={c.id} onClick={()=>void loadConversation(c.id)} className="w-full text-left px-3 py-2.5 rounded-xl text-sm truncate mb-1" style={{background:conversation===c.id?'color-mix(in srgb, var(--cosmos-primary) 14%, transparent)':'transparent'}}>{c.title||'New chat'}</button>):<div className="px-3 py-3 text-xs opacity-55 leading-5">Sign in to save chats, get a larger daily allowance and continue conversations later.</div>}</div>
      <div className="p-3 border-t space-y-1" style={{borderColor:'var(--cosmos-divider)'}}><a href="/my-account" className="block rounded-xl px-3 py-2 text-sm hover:opacity-80">Account & settings</a><a href="/docs" className="block rounded-xl px-3 py-2 text-sm hover:opacity-80">Docs</a><a href="/download/otya-player" className="block rounded-xl px-3 py-2 text-sm hover:opacity-80">Get OTYA Player</a>{user?<><div className="px-3 pt-2 text-xs truncate opacity-60">{user.email}</div><button onClick={logout} className="w-full text-left rounded-xl px-3 py-2 text-sm">Sign out</button></>:<button onClick={()=>setShowLogin(true)} className="w-full text-left rounded-xl px-3 py-2 text-sm font-bold">Sign in to save chats</button>}</div>
    </aside>

    <section className="min-w-0 flex-1 flex flex-col relative">
      <header className="h-14 shrink-0 px-3 sm:px-5 flex items-center border-b" style={{borderColor:'var(--cosmos-divider)'}}><button className="md:hidden w-9 h-9 rounded-lg mr-2" onClick={()=>setSidebar(true)}>☰</button><div className="font-bold mr-2">OTYA AI</div>{token?<select aria-label="AI model" value={model} onChange={e=>chooseModel(e.target.value)} className="max-w-[190px] bg-transparent border rounded-lg px-2 py-1.5 text-sm" style={{borderColor:'var(--cosmos-divider)'}}>{models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select>:<button onClick={()=>setShowLogin(true)} className="text-xs rounded-full border px-2.5 py-1.5" style={{borderColor:'var(--cosmos-divider)'}}>OTYA Fast · Sign in for more models</button>}<div className="ml-auto text-[11px] opacity-50 hidden sm:flex items-center gap-3">{quota&&<span>{quota.remaining} credits left</span>}<span>{selected?`${selected.provider} · ${selected.tier}`:'General assistant'}</span></div></header>

      <div ref={scrollRef} className="flex-1 overflow-y-auto overscroll-contain">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 pt-5 pb-36">
          {messages.length===0?<div className="min-h-[58vh] flex flex-col items-center justify-center text-center"><div className="w-14 h-14 rounded-2xl grid place-items-center text-2xl font-black text-white cosmos-button">O</div><h1 className="text-3xl sm:text-4xl font-black mt-5">What can I help with?</h1><p className="mt-2 max-w-xl opacity-60 text-sm">Ask anything — general knowledge, writing, learning, ideas, coding, everyday questions, or OTYA Player help.</p>{!token&&<button onClick={()=>setShowLogin(true)} className="mt-4 text-xs rounded-full border px-3 py-2" style={{borderColor:'var(--cosmos-divider)'}}>Guest uses OTYA Fast · Sign in to save chats and choose models</button>}<div className="grid sm:grid-cols-2 gap-2 mt-7 w-full max-w-xl">{['Explain quantum computing simply','Help me write a professional message','Who is the president of Uganda?','What is the latest OTYA version?'].map(x=><button key={x} onClick={()=>{setInput(x);setTimeout(()=>textRef.current?.focus(),20)}} className="rounded-xl border p-3 text-left text-sm hover:opacity-80" style={{borderColor:'var(--cosmos-divider)',background:'var(--cosmos-card)'}}>{x}</button>)}</div></div>:
          <div className="space-y-7">{messages.map((m,i)=>m.role==='user'?<div key={i} className="flex justify-end"><div className="max-w-[86%] rounded-3xl px-4 py-3 text-[15px] whitespace-pre-wrap" style={{background:'color-mix(in srgb, var(--cosmos-primary) 18%, var(--cosmos-card))'}}>{m.content}</div></div>:<article key={i} className="flex gap-3"><div className="mt-0.5 w-8 h-8 shrink-0 rounded-lg grid place-items-center text-xs font-black text-white cosmos-button">O</div><div className="min-w-0 flex-1"><div className="whitespace-pre-wrap text-[15px] sm:text-[16px] leading-7">{m.content}</div><button onClick={()=>navigator.clipboard?.writeText(m.content)} className="mt-2 text-xs opacity-45 hover:opacity-80">Copy</button></div></article>)}{busy&&<div className="flex gap-3 items-center"><div className="w-8 h-8 rounded-lg grid place-items-center text-xs font-black text-white cosmos-button">O</div><div className="flex gap-1"><span className="w-2 h-2 rounded-full bg-current opacity-30 animate-pulse"/><span className="w-2 h-2 rounded-full bg-current opacity-50 animate-pulse"/><span className="w-2 h-2 rounded-full bg-current opacity-70 animate-pulse"/></div></div>}{error&&<div className="rounded-xl px-3 py-2 text-sm text-red-500 border border-red-500/20">{error}</div>}</div>}
        </div>
      </div>

      <div className="absolute inset-x-0 bottom-0 px-3 sm:px-5 pb-[max(10px,env(safe-area-inset-bottom))] pt-5 bg-gradient-to-t from-[var(--cosmos-scaffold)] via-[var(--cosmos-scaffold)] to-transparent"><div className="max-w-3xl mx-auto"><div className="rounded-[26px] border p-2 flex items-end shadow-lg" style={{background:'var(--cosmos-card)',borderColor:'var(--cosmos-divider)'}}><textarea ref={textRef} rows={1} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}}} className="min-h-11 max-h-40 flex-1 resize-none bg-transparent outline-none px-3 py-2.5 leading-6" placeholder="Message OTYA AI"/><button aria-label="Send" onClick={()=>void send()} disabled={busy||!input.trim()} className="cosmos-button w-10 h-10 rounded-full grid place-items-center font-black disabled:opacity-30">↑</button></div><p className="text-[10px] opacity-45 text-center mt-1.5">OTYA AI can make mistakes. {token?'Chats are saved to your account.':'Guest chats are temporary.'}</p></div></div>
    </section>

    {showLogin&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/55 p-4"><form onSubmit={login} className="w-full max-w-sm rounded-2xl border p-6 shadow-2xl" style={{background:'var(--cosmos-card)',borderColor:'var(--cosmos-divider)'}}><div className="flex justify-between items-center"><h2 className="text-xl font-black">Sign in to OTYA</h2><button type="button" onClick={()=>setShowLogin(false)} className="text-2xl">×</button></div><p className="text-sm opacity-60 mt-1 mb-4">Save conversations, get more daily credits and unlock the model selector.</p><input type="email" autoComplete="email" className="w-full rounded-xl border bg-transparent px-4 py-3 mb-3" style={{borderColor:'var(--cosmos-divider)'}} placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" autoComplete="current-password" className="w-full rounded-xl border bg-transparent px-4 py-3" style={{borderColor:'var(--cosmos-divider)'}} placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<p className="text-xs text-red-500 mt-2">{error}</p>}<button disabled={authBusy} className="cosmos-button w-full rounded-xl py-3 mt-3 font-bold">{authBusy?'Signing in…':'Sign in'}</button></form></div>}
  </main>
}
