'use client'

import { FormEvent, KeyboardEvent, useEffect, useMemo, useState } from 'react'

type ChatMessage = { role:'user'|'assistant'; content:string; handoff?:boolean; failed?:boolean }
const prompts=['What can Otya do for me?','How do I send a large video with Otya Transfer?','Why can a video have picture but no sound?','Help me discover something new to play.']

function OtyaMark({thinking=false}:{thinking?:boolean}){return <span aria-hidden="true" className={thinking?'inline-flex h-8 w-8 animate-pulse items-center justify-center':'inline-flex h-8 w-8 items-center justify-center'}><img src="/otya-icon.svg" alt="" width={32} height={32} className="h-8 w-8"/></span>}

export function OtyaAssistPrompt(){
  const [query,setQuery]=useState(''); const [messages,setMessages]=useState<ChatMessage[]>([]); const [loading,setLoading]=useState(false); const [guestId,setGuestId]=useState(''); const [showHandoff,setShowHandoff]=useState(false); const [email,setEmail]=useState(''); const [handoffStatus,setHandoffStatus]=useState('')
  useEffect(()=>{let id=localStorage.getItem('otya_ai_guest')||''; if(!id){id=crypto.randomUUID()+crypto.randomUUID();localStorage.setItem('otya_ai_guest',id)} setGuestId(id)},[])
  const lastUserMessage=useMemo(()=>[...messages].reverse().find(m=>m.role==='user')?.content||'',[messages])
  const handoffAvailable=Boolean([...messages].reverse().find(m=>m.role==='assistant')?.handoff)

  async function ask(question:string){const q=question.trim(); if(!q||!guestId||loading)return; const history=messages.slice(-20).map(m=>({role:m.role,content:m.content})); setQuery('');setLoading(true);setShowHandoff(false);setHandoffStatus('');setMessages(c=>[...c,{role:'user',content:q}]);try{const response=await fetch('/api/ai/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:q,history,guest_id:guestId,surface:'website-chat'})});const data=await response.json().catch(()=>({})) as {answer?:string;error?:string;handoff_available?:boolean};if(!response.ok)throw new Error(data.error||'unavailable');setMessages(c=>[...c,{role:'assistant',content:data.answer||'I could not answer that yet. Try asking in another way.',handoff:Boolean(data.handoff_available)}])}catch{setMessages(c=>[...c,{role:'assistant',content:'I cannot reach the online service right now. You can keep using Otya normally and try again when your connection returns.',failed:true}])}finally{setLoading(false)}}
  async function submit(event:FormEvent){event.preventDefault();await ask(query)}
  function onComposerKeyDown(event:KeyboardEvent<HTMLTextAreaElement>){if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();void ask(query)}}
  function newChat(){if(loading)return;setMessages([]);setQuery('');setShowHandoff(false);setHandoffStatus('')}
  async function retryLast(){if(!lastUserMessage||loading)return;setMessages(c=>c.filter((_,i)=>!(i===c.length-1&&c[i]?.failed)));await ask(lastUserMessage)}
  async function requestHandoff(){if(!lastUserMessage||!email.trim()||loading)return;setLoading(true);setHandoffStatus('');try{const response=await fetch('/api/ai/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:lastUserMessage,guest_id:guestId,surface:'website-chat',request_handoff:true,contact_email:email.trim()})});const data=await response.json().catch(()=>({})) as {error?:string;ticket?:string;message?:string};if(!response.ok)throw new Error(data.error||'Could not notify support.');setHandoffStatus(`${data.message||'Support has been notified.'}${data.ticket?` Ticket: ${data.ticket}`:''}`);setShowHandoff(false)}catch(error){setHandoffStatus((error as Error).message||'Could not notify support. Please email support@petersmartlink.com.')}finally{setLoading(false)}}

  return <section className="my-6 overflow-hidden rounded-[28px] border backdrop-blur-xl" style={{borderColor:'color-mix(in srgb,var(--cosmos-divider) 78%,transparent)',background:'linear-gradient(145deg,color-mix(in srgb,var(--cosmos-card) 90%,var(--cosmos-primary)),color-mix(in srgb,var(--cosmos-card) 94%,var(--cosmos-cyan)))'}}>
    <div className="flex items-center gap-3 border-b px-4 py-3 sm:px-5" style={{borderColor:'var(--cosmos-divider)'}}><OtyaMark/><div className="min-w-0 flex-1"><div className="font-extrabold tracking-tight">Ask Otya</div><div className="text-xs otya-muted">Ask naturally. Follow up. Keep the conversation moving.</div></div>{messages.length>0&&<button type="button" onClick={newChat} disabled={loading} className="min-h-11 rounded-full border px-3 text-sm font-bold disabled:opacity-50" style={{borderColor:'var(--cosmos-divider)'}}>New chat</button>}</div>
    <div className="min-h-[300px] px-4 py-5 sm:px-6" aria-live="polite">
      {messages.length===0?<div className="mx-auto max-w-2xl py-5 sm:py-9"><OtyaMark/><h2 className="mt-5 text-2xl sm:text-3xl font-extrabold tracking-[-.04em]">How can I help?</h2><p className="mt-2 text-sm leading-relaxed otya-muted">Ask about Otya, playback, Transfer, files, updates, your account, or music discovery.</p><div className="mt-6 grid gap-2 sm:grid-cols-2">{prompts.map(prompt=><button key={prompt} type="button" onClick={()=>void ask(prompt)} className="min-h-12 rounded-2xl border p-4 text-left text-sm font-semibold hover:-translate-y-0.5" style={{borderColor:'var(--cosmos-divider)',background:'color-mix(in srgb,var(--cosmos-surface) 80%,transparent)'}}>{prompt}</button>)}</div></div>
      :<div className="mx-auto max-w-3xl space-y-5">{messages.map((message,index)=>message.role==='user'?<div key={index} className="ml-auto max-w-[88%] rounded-3xl rounded-br-lg px-4 py-3 text-sm leading-relaxed" style={{background:'color-mix(in srgb,var(--cosmos-primary) 13%,var(--cosmos-surface))'}}>{message.content}</div>:<div key={index} className="max-w-[94%]"><div className="mb-2 flex items-center gap-2"><OtyaMark/><span className="text-xs font-extrabold">Otya</span></div><div className="whitespace-pre-wrap text-sm leading-7">{message.content}</div><div className="mt-2 flex flex-wrap gap-2"><button type="button" onClick={()=>void navigator.clipboard.writeText(message.content)} className="min-h-11 rounded-full px-3 text-xs font-bold otya-muted">Copy</button>{message.failed&&<button type="button" onClick={()=>void retryLast()} disabled={loading} className="min-h-11 rounded-full px-3 text-xs font-bold">Retry</button>}{message.handoff&&<button type="button" onClick={()=>setShowHandoff(true)} className="min-h-11 rounded-full px-3 text-xs font-bold">Talk to support</button>}</div></div>)}{loading&&<div className="flex items-center gap-3 py-2" role="status" aria-label="Otya is thinking"><OtyaMark thinking/><span className="text-sm otya-muted">Thinking…</span></div>}</div>}
    </div>
    {showHandoff&&handoffAvailable&&<div className="mx-4 mb-4 rounded-2xl border p-4 sm:mx-6" style={{borderColor:'var(--cosmos-divider)',background:'var(--cosmos-surface)'}}><div className="font-extrabold">Talk to support</div><p className="mt-1 text-xs otya-muted">Enter your email and Otya will send the last question to support with a ticket number.</p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="email" placeholder="Your email" className="min-h-12 min-w-0 flex-1 rounded-xl border px-3 text-sm outline-none bg-transparent" style={{borderColor:'var(--cosmos-divider)'}}/><button type="button" disabled={loading||!email.trim()} onClick={()=>void requestHandoff()} className="cosmos-button min-h-12 rounded-xl px-4 text-sm font-bold disabled:opacity-50">Send</button></div></div>}
    {handoffStatus&&<div className="mx-4 mb-4 text-sm otya-muted sm:mx-6" aria-live="polite">{handoffStatus}</div>}
    <form onSubmit={submit} className="border-t p-3 sm:p-4" style={{borderColor:'var(--cosmos-divider)'}}><div className="mx-auto flex max-w-3xl items-end gap-2 rounded-2xl border p-2" style={{borderColor:'var(--cosmos-divider)',background:'color-mix(in srgb,var(--cosmos-surface) 78%,transparent)'}}><textarea value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={onComposerKeyDown} rows={1} placeholder="Message Ask Otya" aria-label="Message Ask Otya" className="max-h-40 min-h-12 min-w-0 flex-1 resize-none bg-transparent px-3 py-3 text-sm outline-none"/><button disabled={loading||!query.trim()||!guestId} aria-label="Send message" className="cosmos-button min-h-12 min-w-12 rounded-xl px-3 text-lg font-extrabold disabled:opacity-50">↑</button></div><p className="mx-auto mt-2 max-w-3xl text-center text-[11px] otya-muted">AI can make mistakes. Never send passwords, OTPs, recovery codes or secret keys.</p></form>
  </section>
}
