'use client'

import { FormEvent, KeyboardEvent, useEffect, useMemo, useRef, useState } from 'react'

type ChatMessage = { role:'user'|'assistant'; content:string; handoff?:boolean; failed?:boolean }
const prompts=['Find music for my mood','Help me with my Otya account','Why does a video have no sound?','Explain something simply']

function OtyaMark({thinking=false}:{thinking?:boolean}){return <span aria-hidden="true" className={thinking?'inline-flex h-8 w-8 animate-pulse items-center justify-center':'inline-flex h-8 w-8 items-center justify-center'}><img src="/otya-icon.svg" alt="" width={32} height={32} className="h-8 w-8"/></span>}

export function OtyaAssistPrompt({compact=false}:{compact?:boolean}){
  const [query,setQuery]=useState(''); const [messages,setMessages]=useState<ChatMessage[]>([]); const [loading,setLoading]=useState(false); const [guestId,setGuestId]=useState(''); const [showHandoff,setShowHandoff]=useState(false); const [email,setEmail]=useState(''); const [handoffStatus,setHandoffStatus]=useState('')
  const scrollRef=useRef<HTMLDivElement>(null)
  useEffect(()=>{let id=localStorage.getItem('otya_ai_guest')||''; if(!id){id=crypto.randomUUID()+crypto.randomUUID();localStorage.setItem('otya_ai_guest',id)} setGuestId(id)},[])
  useEffect(()=>{scrollRef.current?.scrollTo({top:scrollRef.current.scrollHeight,behavior:'smooth'})},[messages,loading])
  const lastUserMessage=useMemo(()=>[...messages].reverse().find(m=>m.role==='user')?.content||'',[messages])
  const handoffAvailable=Boolean([...messages].reverse().find(m=>m.role==='assistant')?.handoff)

  async function ask(question:string){const q=question.trim(); if(!q||!guestId||loading)return; const history=messages.slice(-20).map(m=>({role:m.role,content:m.content})); setQuery('');setLoading(true);setShowHandoff(false);setHandoffStatus('');setMessages(c=>[...c,{role:'user',content:q}]);try{const response=await fetch('/api/ai/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:q,history,guest_id:guestId,surface:'website-chat'})});const data=await response.json().catch(()=>({})) as {answer?:string;error?:string;handoff_available?:boolean};if(!response.ok)throw new Error(data.error||'unavailable');setMessages(c=>[...c,{role:'assistant',content:data.answer||'I could not answer that yet. Try asking another way.',handoff:Boolean(data.handoff_available)}])}catch{setMessages(c=>[...c,{role:'assistant',content:'I cannot reach the online service right now. Try again when your connection is stable.',failed:true}])}finally{setLoading(false)}}
  async function submit(event:FormEvent){event.preventDefault();await ask(query)}
  function onComposerKeyDown(event:KeyboardEvent<HTMLTextAreaElement>){if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();void ask(query)}}
  function newChat(){if(loading)return;setMessages([]);setQuery('');setShowHandoff(false);setHandoffStatus('')}
  async function retryLast(){if(!lastUserMessage||loading)return;setMessages(c=>c.filter((_,i)=>!(i===c.length-1&&c[i]?.failed)));await ask(lastUserMessage)}
  async function requestHandoff(){if(!lastUserMessage||!email.trim()||loading)return;setLoading(true);setHandoffStatus('');try{const response=await fetch('/api/ai/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:lastUserMessage,guest_id:guestId,surface:'website-chat',request_handoff:true,contact_email:email.trim()})});const data=await response.json().catch(()=>({})) as {error?:string;ticket?:string;message?:string};if(!response.ok)throw new Error(data.error||'Could not notify support.');setHandoffStatus(`${data.message||'Otya Support has been notified.'}${data.ticket?` Ticket: ${data.ticket}`:''}`);setShowHandoff(false)}catch(error){setHandoffStatus((error as Error).message||'Could not notify support.')}finally{setLoading(false)}}

  return <section className={`${compact?'flex-1 min-h-0':'my-6 h-[min(720px,72dvh)]'} flex flex-col overflow-hidden rounded-[26px] border backdrop-blur-xl`} style={{borderColor:'color-mix(in srgb,var(--cosmos-divider) 78%,transparent)',background:'linear-gradient(145deg,color-mix(in srgb,var(--cosmos-card) 90%,var(--cosmos-primary)),color-mix(in srgb,var(--cosmos-card) 94%,var(--cosmos-cyan)))'}}>
    <div className="shrink-0 flex items-center gap-3 border-b px-4 py-3" style={{borderColor:'var(--cosmos-divider)'}}><OtyaMark/><div className="min-w-0 flex-1"><div className="font-extrabold tracking-tight">Ask Otya</div><div className="text-xs otya-muted">Short answers. Follow up anytime.</div></div>{messages.length>0&&<button type="button" onClick={newChat} disabled={loading} className="min-h-10 rounded-full border px-3 text-xs font-bold disabled:opacity-50" style={{borderColor:'var(--cosmos-divider)'}}>New</button>}</div>
    <div ref={scrollRef} className="flex-1 min-h-0 overflow-y-auto overscroll-contain px-4 py-4 sm:px-5" aria-live="polite">
      {messages.length===0?<div className="mx-auto max-w-2xl py-3 sm:py-7"><h2 className="text-xl sm:text-2xl font-extrabold tracking-[-.04em]">Start anywhere.</h2><div className="mt-5 grid gap-2 sm:grid-cols-2">{prompts.map(prompt=><button key={prompt} type="button" onClick={()=>void ask(prompt)} className="min-h-12 rounded-2xl border p-3.5 text-left text-sm font-semibold transition hover:-translate-y-0.5" style={{borderColor:'var(--cosmos-divider)',background:'color-mix(in srgb,var(--cosmos-surface) 80%,transparent)'}}>{prompt}</button>)}</div></div>
      :<div className="mx-auto max-w-3xl space-y-5">{messages.map((message,index)=>message.role==='user'?<div key={index} className="ml-auto max-w-[88%] rounded-3xl rounded-br-lg px-4 py-3 text-sm leading-relaxed" style={{background:'color-mix(in srgb,var(--cosmos-primary) 13%,var(--cosmos-surface))'}}>{message.content}</div>:<div key={index} className="max-w-[94%]"><div className="mb-2 flex items-center gap-2"><OtyaMark/><span className="text-xs font-extrabold">Otya</span></div><div className="whitespace-pre-wrap text-sm leading-7">{message.content}</div><div className="mt-2 flex flex-wrap gap-2"><button type="button" onClick={()=>void navigator.clipboard.writeText(message.content)} className="min-h-10 rounded-full px-3 text-xs font-bold otya-muted">Copy</button>{message.failed&&<button type="button" onClick={()=>void retryLast()} disabled={loading} className="min-h-10 rounded-full px-3 text-xs font-bold">Retry</button>}{message.handoff&&<button type="button" onClick={()=>setShowHandoff(true)} className="min-h-10 rounded-full px-3 text-xs font-bold">Support</button>}</div></div>)}{loading&&<div className="flex items-center gap-3 py-2" role="status" aria-label="Otya is thinking"><OtyaMark thinking/><span className="text-sm otya-muted">Thinking…</span></div>}</div>}
    </div>
    {showHandoff&&handoffAvailable&&<div className="shrink-0 mx-3 mb-2 rounded-2xl border p-3" style={{borderColor:'var(--cosmos-divider)',background:'var(--cosmos-surface)'}}><div className="flex flex-col gap-2 sm:flex-row"><input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="email" placeholder="Your email" className="min-h-11 min-w-0 flex-1 rounded-xl border px-3 text-sm outline-none bg-transparent" style={{borderColor:'var(--cosmos-divider)'}}/><button type="button" disabled={loading||!email.trim()} onClick={()=>void requestHandoff()} className="cosmos-button min-h-11 rounded-xl px-4 text-sm font-bold disabled:opacity-50">Send</button></div></div>}
    {handoffStatus&&<div className="shrink-0 mx-4 mb-2 text-xs otya-muted" aria-live="polite">{handoffStatus}</div>}
    <form onSubmit={submit} className="shrink-0 border-t p-3" style={{borderColor:'var(--cosmos-divider)'}}><div className="mx-auto flex max-w-3xl items-end gap-2 rounded-2xl border p-2" style={{borderColor:'var(--cosmos-divider)',background:'color-mix(in srgb,var(--cosmos-surface) 78%,transparent)'}}><textarea value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={onComposerKeyDown} rows={1} placeholder="Message Ask Otya" aria-label="Message Ask Otya" className="max-h-32 min-h-11 min-w-0 flex-1 resize-none bg-transparent px-3 py-2.5 text-sm outline-none"/><button disabled={loading||!query.trim()||!guestId} aria-label="Send message" className="cosmos-button min-h-11 min-w-11 rounded-xl px-3 text-lg font-extrabold disabled:opacity-50">↑</button></div></form>
  </section>
}
