import { appendMessage, getOrCreateConversation, hashIdentity, readConversation } from './conversations.mjs'
const MODEL='@cf/meta/llama-3.1-8b-instruct-fast'
const TELEGRAM_API='https://api.telegram.org'
const clean=(v,max=5000)=>String(v??'').replace(/[\u0000-\u001f]/g,' ').trim().slice(0,max)
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}})
const aiText=r=>typeof r?.response==='string'?r.response:(typeof r?.choices?.[0]?.message?.content==='string'?r.choices[0].message.content:'')
async function runAi(env,messages){if(!env.AI?.run)throw new Error('AI unavailable');return clean(aiText(await env.AI.run(env.OTYA_AI_MODEL||MODEL,{messages})),7000)}
const system=(env)=>`You are OTYA AI, the official customer assistant for OTYA Player. Help with playback, downloads, media library, updates, account access, verification, privacy, Terms and general troubleshooting. Be conversational and concise. Never expose or request passwords, OTPs, JWTs, API keys, secrets, payment credentials or private backend information. You have no access to admin Gmail, GitHub, Cloudflare, private customer lists or infrastructure tools. Never claim an account action, refund, deletion, deployment or email send occurred unless an approved verified backend action confirms it. For account-specific or sensitive requests direct the user to the signed-in app flow or support@petersmartlink.com. Official download: https://petersmartlink.com/download/otya-player. Official Telegram: ${env.TELEGRAM_CHANNEL_URL||'https://t.me/otyaplayer'}.`
async function rate(env,key,limit=20,seconds=60){if(!env.KV)return true;const bucket=Math.floor(Date.now()/(seconds*1000));const k=`ai:client-rate:${key}:${bucket}`;const n=Number(await env.KV.get(k)||0);if(n>=limit)return false;await env.KV.put(k,String(n+1),{expirationTtl:seconds*2});return true}
async function conversationReply(env,{ownerType,identity,message,channel,conversationId}){const ownerKey=await hashIdentity(env,identity);const conv=await getOrCreateConversation(env,{ownerType,ownerKey,conversationId});const previous=await readConversation(env,{ownerType,ownerKey,conversationId:conv.id,limit:18});const history=(previous?.messages||[]).map(x=>({role:x.role,content:clean(x.content,3000)}));await appendMessage(env,{conversationId:conv.id,role:'user',content:message,channel});const answer=await runAi(env,[{role:'system',content:system(env)},...history,{role:'user',content:clean(message,2500)}]);await appendMessage(env,{conversationId:conv.id,role:'assistant',content:answer,channel});return{conversation_id:conv.id,answer}}
async function telegram(env,method,body){if(!env.TELEGRAM_BOT_TOKEN)throw new Error('Telegram unavailable');const r=await fetch(`${TELEGRAM_API}/bot${env.TELEGRAM_BOT_TOKEN}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error('Telegram send failed')}
export async function handleSharedTelegram(request,env){const url=new URL(request.url);if(!url.pathname.endsWith('/webhook'))return null;if(request.method!=='POST')return json({error:'Method not allowed'},405);if(!env.TELEGRAM_WEBHOOK_SECRET)return json({error:'Telegram webhook unavailable'},503);if((request.headers.get('X-Telegram-Bot-Api-Secret-Token')||'')!==env.TELEGRAM_WEBHOOK_SECRET)return json({error:'Unauthorized'},401);const update=await request.json().catch(()=>null);const m=update?.message;const chatId=m?.chat?.id;const sender=m?.from?.id??chatId;const text=clean(m?.text,2500);if(!chatId||m?.chat?.type!=='private'||!text)return json({ok:true});const identity=`telegram:${sender}`;const key=await hashIdentity(env,identity);if(!(await rate(env,key,20,60))){await telegram(env,'sendMessage',{chat_id:chatId,text:'You are sending messages too quickly. Please wait a moment.',disable_web_page_preview:true});return json({ok:true,rate_limited:true})}let answer;if(text==='/start')answer='Welcome to OTYA AI. I am the same OTYA support assistant used on the website. Ask me about playback, downloads, accounts, updates or troubleshooting.';else if(text==='/download')answer='Official OTYA Player download: https://petersmartlink.com/download/otya-player';else if(text==='/privacy')answer='Never send passwords, OTPs, payment credentials or secret keys here. Sensitive account actions require a verified OTYA flow.';else{try{answer=(await conversationReply(env,{ownerType:'client',identity,message:text,channel:'telegram'})).answer}catch(e){console.error('[telegram-shared]',e?.message);answer='I cannot answer reliably right now. Please contact support@petersmartlink.com.'}}await telegram(env,'sendMessage',{chat_id:chatId,text:clean(answer,3500),disable_web_page_preview:true});return json({ok:true})}
export async function handlePublicChat(request,env){const url=new URL(request.url);if(request.method==='GET'){const guest=clean(url.searchParams.get('guest_id'),120);const id=clean(url.searchParams.get('conversation_id'),80);if(guest.length<20||!id)return json({error:'guest_id and conversation_id are required'},400);const identity=`web:${guest}`;const ownerKey=await hashIdentity(env,identity);const conversation=await readConversation(env,{ownerType:'client',ownerKey,conversationId:id,limit:80});return conversation?json({ok:true,conversation}):json({error:'Conversation not found'},404)}if(request.method!=='POST')return json({error:'Method not allowed'},405);const body=await request.json().catch(()=>({}));const message=clean(body.message,2500);if(!message)return json({error:'message is required'},400);const guest=clean(body.guest_id,120);if(guest.length<20)return json({error:'guest_id is required'},400);const ip=request.headers.get('CF-Connecting-IP')||'unknown';const identity=`web:${guest}`;const rateKey=await hashIdentity(env,`${identity}:${ip}`);if(!(await rate(env,rateKey,15,60)))return json({error:'Too many messages. Please wait a moment.'},429);try{return json({ok:true,...await conversationReply(env,{ownerType:'client',identity,message,channel:'web',conversationId:clean(body.conversation_id,80)})})}catch(e){console.error('[public-ai]',e?.message);return json({error:'OTYA AI is temporarily unavailable'},503)}}
