import { gmailStatus } from './gmail-connector.mjs'
import { appendMessage, listConversations, newConversation, readConversation, getOrCreateConversation, archiveConversation } from './conversations.mjs'
const DEFAULT_MODEL='@cf/meta/llama-3.1-8b-instruct-fast'
const clean=(v,max=5000)=>String(v??'').replace(/[\u0000-\u001f]/g,' ').trim().slice(0,max)
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}})
const aiText=r=>typeof r?.response==='string'?r.response:(typeof r?.choices?.[0]?.message?.content==='string'?r.choices[0].message.content:'')
const parse=s=>{try{const m=String(s||'').match(/\{[\s\S]*\}/);return m?JSON.parse(m[0]):null}catch{return null}}
function internalAuthorized(request,env){return Boolean(env.INTERNAL_SECRET)&&(request.headers.get('X-OTYA-Internal-Secret')||'')===env.INTERNAL_SECRET}
async function runAi(env,messages){if(!env.AI?.run)throw new Error('AI binding unavailable');return clean(aiText(await env.AI.run(env.OTYA_AI_MODEL||DEFAULT_MODEL,{messages})),12000)}
async function pluginRegistry(env){const gmail=await gmailStatus(env);return [
{id:'resend',name:'Resend',category:'Email',status:env.RESEND_API_KEY?'connected':'setup_required',capabilities:['support inbox','personal replies','transactional email'],write:true},
{id:'telegram',name:'Telegram',category:'Messaging',status:env.TELEGRAM_BOT_TOKEN&&env.TELEGRAM_WEBHOOK_SECRET?'connected':'setup_required',capabilities:['same OTYA AI','private support','server conversation memory'],write:true},
{id:'otya',name:'OTYA System',category:'System',status:env.DB&&env.KV?'connected':'degraded',capabilities:['feedback','crashes','releases','usage signals','AI queue'],write:false},
{id:'gmail',name:'Gmail',category:'Email',status:gmail.connected?'connected':gmail.configured?'ready_to_connect':'setup_required',capabilities:['read mailbox','search threads','read messages','send approved mail'],write:true,setup_hint:gmail.connected?'Connected through encrypted OAuth tokens.':gmail.configured?'Ready for Google consent.':'Requires a Google OAuth Web client and client secret.'},
{id:'github',name:'GitHub',category:'Developer',status:'available_next',capabilities:['issues','pull requests','workflow status','release context'],write:true,setup_hint:'Use a dedicated GitHub App/token with least-privilege repository permissions.'},
{id:'cloudflare',name:'Cloudflare',category:'Infrastructure',status:'available_next',capabilities:['Worker health','queues','D1/KV/R2 status','deployment checks'],write:true,setup_hint:'Use a scoped Cloudflare API token; destructive actions require explicit approval.'},]}
async function systemSnapshot(env){const out={generated_at:new Date().toISOString(),database:Boolean(env.DB),kv:Boolean(env.KV),ai:Boolean(env.AI?.run),push:Boolean(env.PUSH_QUEUE?.send)};if(env.DB?.prepare){try{out.feedback_7d=(await env.DB.prepare("SELECT COUNT(*) count FROM feedback WHERE created_at>=datetime('now','-7 days')").first())?.count||0}catch{}try{out.crashes_7d=(await env.DB.prepare("SELECT COUNT(*) count FROM crash_reports WHERE created_at>=datetime('now','-7 days')").first())?.count||0}catch{}try{out.downloads_7d=(await env.DB.prepare("SELECT COUNT(*) count FROM downloads WHERE created_at>=datetime('now','-7 days')").first())?.count||0}catch{}try{out.latest_release=await env.DB.prepare('SELECT tag,version,released_at FROM releases ORDER BY released_at DESC LIMIT 1').first()}catch{}}return out}
async function recentFeedback(env){if(!env.DB?.prepare)return[];const{results=[]}=await env.DB.prepare("SELECT id,category,sentiment,description,created_at FROM feedback ORDER BY created_at DESC LIMIT 20").all();return results.map(x=>({...x,description:clean(x.description,700)}))}
async function recentCrashes(env){if(!env.DB?.prepare)return[];const{results=[]}=await env.DB.prepare("SELECT group_id,error_type,COUNT(*) count,MAX(created_at) latest FROM crash_reports WHERE created_at>=datetime('now','-14 days') GROUP BY group_id,error_type ORDER BY count DESC LIMIT 15").all();return results}
async function recentReleases(env){if(!env.DB?.prepare)return[];const{results=[]}=await env.DB.prepare('SELECT tag,version,version_code,changelog,released_at FROM releases ORDER BY released_at DESC LIMIT 8').all();return results.map(x=>({...x,changelog:clean(x.changelog,1000)}))}
async function routeTool(env,message){const tools=['none','system_status','plugins','feedback_summary','crash_summary','release_summary','support_inbox'];const prompt=`Choose at most one read-only OTYA admin tool that materially helps answer the user. Tools: ${tools.join(', ')}. Use none for ordinary conversation, writing or planning. Return JSON only: {"tool":"name","reason":"brief"}.\nUser: ${clean(message,1800)}`;const routed=parse(await runAi(env,[{role:'system',content:'You are a conservative tool router. Never choose a write action.'},{role:'user',content:prompt}]))||{};return tools.includes(routed.tool)?routed:{tool:'none',reason:'No safe tool selected.'}}
async function toolData(env,tool){if(tool==='plugins')return{plugins:await pluginRegistry(env)};if(tool==='system_status')return{status:await systemSnapshot(env)};if(tool==='feedback_summary')return{feedback:await recentFeedback(env)};if(tool==='crash_summary')return{crashes:await recentCrashes(env)};if(tool==='release_summary')return{releases:await recentReleases(env)};if(tool==='support_inbox')return{support_workspace:'/admin/ai',note:'Support inbox and reply approval are available from the Console sidebar.'};return null}
const ownerType='admin';const ownerKey='primary'
async function chat(env,body){const message=clean(body?.message,4000);if(!message)throw new Error('message is required');const conv=await getOrCreateConversation(env,{ownerType,ownerKey,conversationId:clean(body?.conversation_id,80)});const existing=await readConversation(env,{ownerType,ownerKey,conversationId:conv.id,limit:24});const history=(existing?.messages||[]).map(x=>({role:x.role,content:clean(x.content,4000)}));const route=await routeTool(env,message);const data=route.tool==='none'?null:await toolData(env,route.tool);const system=`You are OTYA AI, the private administrator assistant for OTYA Player and PeterSmart Link. Be conversational, concise, practical and technically grounded. You can reason, draft text and use connected read-only tools. Never pretend a plugin is connected when it is not. Never reveal secrets, tokens, OTPs or credentials. Never execute or claim destructive/write actions from chat. Sending email, push, deployment, deletion or infrastructure changes require a separate explicit approval flow. Use supplied tool data faithfully.`;const context=data?`\nRead-only tool used: ${route.tool}\nTool data:\n${JSON.stringify(data).slice(0,12000)}`:'';await appendMessage(env,{conversationId:conv.id,role:'user',content:message,channel:'console'});const answer=await runAi(env,[{role:'system',content:system},...history,{role:'user',content:`${message}${context}`}]);await appendMessage(env,{conversationId:conv.id,role:'assistant',content:answer||'I could not produce a response.',channel:'console'});return{conversation_id:conv.id,answer:answer||'I could not produce a response.',tool:route.tool==='none'?null:route.tool,tool_reason:route.reason,data}}
export async function handleConsoleAdmin(request,env){if(!internalAuthorized(request,env))return json({error:'Unauthorized'},401);const url=new URL(request.url);try{
if(url.pathname.endsWith('/plugins')&&request.method==='GET')return json({ok:true,plugins:await pluginRegistry(env)})
if(url.pathname.endsWith('/status')&&request.method==='GET')return json({ok:true,status:await systemSnapshot(env)})
if(url.pathname.endsWith('/conversations')&&request.method==='GET')return json({ok:true,conversations:await listConversations(env,{ownerType,ownerKey,limit:40})})
if(url.pathname.endsWith('/conversation')&&request.method==='GET'){const id=url.searchParams.get('id');if(!id)return json({error:'id is required'},400);const conversation=await readConversation(env,{ownerType,ownerKey,conversationId:id,limit:80});return conversation?json({ok:true,conversation}):json({error:'Conversation not found'},404)}
if(url.pathname.endsWith('/conversation/new')&&request.method==='POST')return json({ok:true,conversation:await newConversation(env,{ownerType,ownerKey})},201)
if(url.pathname.endsWith('/conversation/archive')&&request.method==='POST'){const body=await request.json().catch(()=>({}));if(!body.id)return json({error:'id is required'},400);await archiveConversation(env,{ownerType,ownerKey,conversationId:body.id});return json({ok:true})}
if((url.pathname.endsWith('/chat')||url.pathname.endsWith('/command'))&&request.method==='POST'){const body=await request.json().catch(()=>({}));return json({ok:true,...await chat(env,body)})}
return json({error:'Not found'},404)}catch(error){console.error('[ai-console]',error?.message);return json({error:'Console tool failed',detail:clean(error?.message,400)},500)}}
