// app/api/device/route.ts
// POST /api/device
// Upserts device info into D1 `devices` table.
// Called once on first launch / version change by the Flutter app.

import { getCloudflareContext } from '@opennextjs/cloudflare'
import { NextRequest, NextResponse } from 'next/server'
import { verifyRequest } from '@/lib/auth'
import { secureJson, errorJson } from '@/lib/response'
import { getDB } from '@/lib/d1'

export interface DevicePayload {
  device_id:       string  // stable UUID generated by the app (stored in SharedPreferences)
  model:           string  // e.g. "Samsung SM-G991B"
  android_version: string  // e.g. "14"
  app_version:     string  // e.g. "1.4.0"
  app_build:       number  // e.g. 7
  arch:            string  // "arm64" | "arm32"
  locale:          string  // e.g. "en_UG"
}

const CORS_HEADERS = {
  'Access-Control-Allow-Origin':  'https://petersmartlink.com',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, X-Otya-Timestamp, X-Otya-Signature, X-Otya-Device-Id',
}

export async function POST(request: NextRequest) {
  const { env } = await getCloudflareContext({ async: true })

  // ── 1. Verify HMAC signature ─────────────────────────────────────────────
  const auth = await verifyRequest(request, env as { OTYA_STORE_ADMIN_TOKEN: string })
  if (!auth.ok) return errorJson(auth.error ?? 'Unauthorized', 401)

  // ── 2. Parse body ────────────────────────────────────────────────────────
  let body: DevicePayload
  try {
    body = await request.json() as DevicePayload
  } catch {
    return errorJson('Invalid JSON body', 400)
  }

  if (!body.device_id || typeof body.device_id !== 'string') {
    return errorJson('device_id is required', 400)
  }

  // ── 3. Upsert into D1 ────────────────────────────────────────────────────
  const db = getDB(env as Record<string, unknown>)

  await db.prepare(`
    INSERT INTO devices (device_id, model, android_version, app_version, app_build, arch, locale, last_seen)
    VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, datetime('now'))
    ON CONFLICT(device_id) DO UPDATE SET
      app_version = excluded.app_version,
      app_build   = excluded.app_build,
      last_seen   = datetime('now')
  `).bind(
    body.device_id,
    body.model           ?? 'unknown',
    body.android_version ?? 'unknown',
    body.app_version     ?? '0.0.0',
    body.app_build       ?? 0,
    body.arch            ?? 'arm64',
    body.locale          ?? 'en',
  ).run()

  return secureJson({ ok: true })
}

export async function OPTIONS() {
  return new NextResponse(null, { headers: CORS_HEADERS })
}
